drop TABLE USERS ;

CREATE TABLE USERS (
 "USER_USERNAME" VARCHAR2(50) NOT NULL,
 "USER_PW" VARCHAR2(50) NOT NULL,
 "USER_EMAIL" VARCHAR2(255) NOT NULL,
 
 "USER_NAME" VARCHAR2(50),
 "USER_GENDER" VARCHAR2(50),
 "USER_PHONE1" VARCHAR2(50),
 "USER_PHONE2" VARCHAR2(50),
 
 "USER_ZIPCODE" VARCHAR2(50),
 "USER_ADDRESS1" VARCHAR2(300),
 "USER_ADDRESS2" VARCHAR2(300),
 
 "USER_ROLE" VARCHAR2(10),
 CONSTRAINT USER_PK PRIMARY KEY (USER_USERNAME)
);

INSERT INTO USERS (USER_USERNAME, USER_PW, USER_EMAIL, USER_NAME, USER_GENDER, USER_PHONE1, USER_PHONE2, USER_ZIPCODE, USER_ADDRESS1, USER_ADDRESS2, USER_ROLE) VALUES 
('Typhoon', 'admin1234', 'admin123@gmail.com', 'JungwooShin', null, null, null, null, null, null, 'admin');


create table zipcode (
 seq NUMBER(10) not null,
 zipcode VARCHAR2(60),
 sido VARCHAR2(60),
 gugun VARCHAR2(60),
 dong VARCHAR2(60),
 bunji VARCHAR2(60),
 constraint PK_ZIPCODE primary key (seq)
);

commit;

select * from zipcode where dong like 'ÀÀ¾Ï%';
