ALTER SESSION SET "_ORACLE_SCRIPT"=true;
    drop user MYHOMEPAGE CASCADE;
    create user MYHOMEPAGE IDENTIFIED by MYHOMEPAGE
     DEFAULT TABLESPACE USERS
     TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, DBA TO MYHOMEPAGE;
     
     
     